import React, { useState } from 'react';
import { 
  X, Compass, Terminal, FlaskConical, Key, Sparkles, BookOpen, 
  CheckCircle2, Clock, Award, ArrowRight, RotateCcw, ShieldAlert,
  HelpCircle, ChevronRight, Download, Share2, Lightbulb, Bookmark
} from 'lucide-react';
import { heistAudio } from './HeistAudioEngine';
import { generateRemediationPlan } from '../data/remediationData';

export default function RemediationRoadmapModal({
  isOpen,
  onClose,
  stageData,
  solvedRoles = {},
  alarmFails = 0,
  onRetryWithHints
}) {
  if (!isOpen) return null;

  const plan = generateRemediationPlan(stageData, solvedRoles, alarmFails);
  const [activeTab, setActiveTab] = useState('roadmap'); // 'roadmap', 'topics', 'drill'
  const [selectedTopicId, setSelectedTopicId] = useState(plan.recommendedTopics[0]?.id || null);
  const [masteredTopics, setMasteredTopics] = useState({});
  const [drillAnswers, setDrillAnswers] = useState({});
  const [drillSubmitted, setDrillSubmitted] = useState({});

  const roleIcons = {
    hacker: Terminal,
    engineer: Compass,
    scientist: FlaskConical,
    cryptographer: Key
  };

  const handleToggleMastery = (topicId) => {
    setMasteredTopics(prev => {
      const next = { ...prev, [topicId]: !prev[topicId] };
      heistAudio.playKeyClick();
      return next;
    });
  };

  const handleSelectDrillOption = (topicId, optIdx) => {
    if (drillSubmitted[topicId]) return;
    setDrillAnswers(prev => ({ ...prev, [topicId]: optIdx }));
    heistAudio.playKeyClick();
  };

  const handleCheckDrill = (topicId, correctIdx) => {
    setDrillSubmitted(prev => ({ ...prev, [topicId]: true }));
    const isCorrect = drillAnswers[topicId] === correctIdx;
    if (isCorrect) {
      heistAudio.playSuccessChime();
      setMasteredTopics(prev => ({ ...prev, [topicId]: true }));
    } else {
      heistAudio.playErrorTone();
    }
  };

  const handleExportRoadmap = () => {
    heistAudio.playKeyClick();
    const markdown = `# 🌲 V.A.U.L.T — Failure Remediation & Learning Roadmap
## Operation: ${plan.stageTitle}
**Estimated Study Time:** ${plan.estimatedStudyTime}
**Diagnostic Summary:** ${plan.diagnosticSummary}

### 🎯 Topics to Master:
${plan.recommendedTopics.map((t, idx) => `
#### ${idx + 1}. ${t.title} (${t.roleName})
- **Discipline:** ${t.discipline}
- **Importance:** ${t.importance} | **Duration:** ${t.duration}
- **Summary:** ${t.summary}
- **Formula / Rule:** \`${t.formula}\`
- **Key Takeaway:** ${t.keyTakeaway}
`).join('\n')}

---
*Generated by V.A.U.L.T Adaptive Heist Intelligence Engine*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `VAULT_Remediation_Roadmap_${stageData?.stageId || 'Custom'}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const selectedTopic = plan.recommendedTopics.find(t => t.id === selectedTopicId) || plan.recommendedTopics[0];
  const masteredCount = Object.values(masteredTopics).filter(Boolean).length;
  const progressPercent = Math.round((masteredCount / Math.max(1, plan.recommendedTopics.length)) * 100);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-5 bg-[#020B06]/85 backdrop-blur-md animate-fade-in overflow-y-auto">
      <div className="max-w-5xl w-full p-5 sm:p-7 space-y-5 rounded-2xl border border-emerald-800/50 bg-[#051C12] shadow-2xl max-h-[92vh] flex flex-col justify-between overflow-hidden text-left">
        
        {/* MODAL HEADER */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 border-b border-emerald-900/60 pb-4">
          <div className="flex items-center space-x-3">
            <div className="bg-[#10B981] p-2 rounded-xl text-[#02140D] shadow-sm">
              <Compass className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <span className="bg-[#FBBF24] text-[#02140D] text-[10px] font-mono font-bold px-2 py-0.5 rounded uppercase">
                  Adaptive Learning Roadmap
                </span>
                <span className="text-xs font-mono text-emerald-300">
                  {plan.estimatedStudyTime} Estimated Study
                </span>
              </div>
              <h2 className="text-xl sm:text-2xl font-bold uppercase tracking-tight text-white mt-0.5 font-game">
                STEM Learning Pathway & Diagnostics
              </h2>
            </div>
          </div>

          <div className="flex items-center space-x-2 self-end sm:self-auto">
            <button
              onClick={handleExportRoadmap}
              className="bg-[#020B06] text-emerald-300 border border-emerald-700/60 px-3 py-1.5 rounded-lg text-xs font-bold uppercase flex items-center space-x-1.5 hover:bg-[#10B981] hover:text-[#02140D] transition-colors font-game"
              title="Download Markdown Study Plan"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Guide</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg border border-emerald-800/60 bg-[#020B06] text-slate-400 hover:text-white hover:bg-red-950 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* DIAGNOSTIC BANNER */}
        <div className="bg-[#020E08] border border-emerald-800/40 rounded-xl p-3.5 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
          <div className="flex items-center space-x-2.5">
            <Lightbulb className="w-5 h-5 text-[#FBBF24] flex-shrink-0" />
            <p className="text-xs text-slate-200 font-mono">
              <strong className="text-[#FBBF24]">Diagnostic:</strong> {plan.diagnosticSummary}
            </p>
          </div>
          <div className="flex items-center space-x-2 text-xs font-mono text-emerald-300 bg-[#041C12] px-3 py-1.5 rounded-lg border border-emerald-800/60 flex-shrink-0">
            <span>Mastery: {masteredCount}/{plan.recommendedTopics.length} ({progressPercent}%)</span>
            <div className="w-16 h-2 bg-emerald-950 rounded-full overflow-hidden border border-emerald-700">
              <div className="h-full bg-[#10B981] transition-all duration-500 rounded-full" style={{ width: `${progressPercent}%` }} />
            </div>
          </div>
        </div>

        {/* VIEW NAVIGATION TABS */}
        <div className="flex bg-[#020B06] p-1 gap-1 rounded-xl border border-emerald-900/60">
          {[
            { id: 'roadmap', label: '🗺️ 4-Phase Pathway', desc: 'Step Progression' },
            { id: 'topics', label: '📚 Core Concepts & Formulas', desc: `${plan.recommendedTopics.length} Key Topics` },
            { id: 'drill', label: '🧪 Practice Drills', desc: 'Concept Checks' }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id);
                heistAudio.playKeyClick();
              }}
              className={`flex-1 py-2 px-3 text-left transition-all rounded-lg ${
                activeTab === tab.id
                  ? 'bg-[#10B981] text-[#02140D] font-bold shadow-sm'
                  : 'text-slate-300 hover:text-white hover:bg-[#072419]'
              }`}
            >
              <span className="block text-xs sm:text-sm font-game font-bold">{tab.label}</span>
              <span className="hidden sm:block text-[10px] opacity-80 font-mono">{tab.desc}</span>
            </button>
          ))}
        </div>

        {/* MAIN BODY CONTENT AREA */}
        <div className="flex-1 overflow-y-auto pr-1 space-y-4 min-h-[320px]">
          
          {/* TAB 1: VISUAL 4-PHASE ROADMAP */}
          {activeTab === 'roadmap' && (
            <div className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                {plan.milestones.map((m, idx) => (
                  <div 
                    key={m.step}
                    className={`p-4 rounded-xl border relative flex flex-col justify-between ${
                      idx === 0 
                        ? 'bg-[#0E3526] border-[#10B981]/60 shadow-md'
                        : idx === 1
                        ? 'bg-[#072419] border-[#FBBF24]/50'
                        : 'bg-[#03140C] border-emerald-900/40 opacity-90'
                    }`}
                  >
                    <div className="space-y-1.5">
                      <div className="flex justify-between items-center">
                        <span className="text-[10px] font-mono font-bold uppercase text-[#FBBF24] bg-[#020B06] px-2 py-0.5 rounded border border-amber-500/40">
                          PHASE 0{m.step}
                        </span>
                        {idx === 0 ? (
                          <CheckCircle2 className="w-4 h-4 text-[#10B981]" />
                        ) : (
                          <Sparkles className="w-4 h-4 text-emerald-400" />
                        )}
                      </div>
                      <h4 className="text-sm font-bold uppercase text-white font-game">{m.title}</h4>
                      <p className="text-xs text-slate-300 leading-snug">{m.desc}</p>
                    </div>

                    <button
                      onClick={() => {
                        if (idx === 1) setActiveTab('topics');
                        if (idx === 2) setActiveTab('drill');
                        if (idx === 3 && onRetryWithHints) onRetryWithHints();
                        heistAudio.playKeyClick();
                      }}
                      className="mt-3.5 w-full bg-[#020B06] text-emerald-300 font-mono text-[10px] font-bold py-1.5 rounded-lg border border-emerald-700/60 hover:bg-[#10B981] hover:text-[#02140D] transition-colors uppercase font-game"
                    >
                      {idx === 0 ? "Diagnosed" : idx === 1 ? "Explore Topics →" : idx === 2 ? "Take Drills →" : "Launch Retry →"}
                    </button>
                  </div>
                ))}
              </div>

              {/* Roles Breakdown Grid */}
              <div className="bg-[#020E08] p-4 rounded-xl border border-emerald-900/60 space-y-3">
                <div className="flex justify-between items-center">
                  <h3 className="text-xs font-mono font-bold uppercase text-emerald-300">
                    Targeted Discipline Focus for This Operation
                  </h3>
                  <span className="text-[10px] font-mono text-slate-400">
                    {plan.focusRoles.length} Active STEM Sectors
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {plan.focusRoles.map(roleKey => {
                    const guide = plan.recommendedTopics.find(t => t.roleKey === roleKey);
                    const RoleIcon = roleIcons[roleKey] || Terminal;
                    const isFailed = plan.failedRoles.includes(roleKey);

                    return (
                      <div 
                        key={roleKey}
                        className={`p-3 rounded-xl border flex items-center justify-between ${
                          isFailed ? 'bg-[#1C0D12] border-red-900/60' : 'bg-[#041C12] border-emerald-800/60'
                        }`}
                      >
                        <div className="flex items-center space-x-3">
                          <div className="p-2 rounded-lg bg-[#020B06] border border-emerald-900/60" style={{ color: guide?.roleColor || '#10B981' }}>
                            <RoleIcon className="w-4 h-4" />
                          </div>
                          <div>
                            <span className="text-xs font-bold uppercase text-white block font-game">
                              {guide?.roleName || roleKey}
                            </span>
                            <span className="text-[10px] font-mono text-emerald-300">
                              {guide?.discipline}
                            </span>
                          </div>
                        </div>

                        <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded uppercase ${
                          isFailed ? 'bg-red-950 text-red-200 border border-red-800' : 'bg-emerald-950 text-emerald-200 border border-emerald-800'
                        }`}>
                          {isFailed ? '⚠️ Unsolved' : '✅ Cleared'}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: RECOMMENDED TOPICS & FORMULAS */}
          {activeTab === 'topics' && (
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
              
              {/* Left Column: Topic List Selector */}
              <div className="lg:col-span-5 space-y-2 max-h-[300px] overflow-y-auto pr-1">
                {plan.recommendedTopics.map((topic) => {
                  const isSelected = selectedTopic?.id === topic.id;
                  const isMastered = !!masteredTopics[topic.id];
                  const RoleIcon = roleIcons[topic.roleKey] || Terminal;

                  return (
                    <button
                      key={topic.id}
                      onClick={() => {
                        setSelectedTopicId(topic.id);
                        heistAudio.playKeyClick();
                      }}
                      className={`w-full p-3 rounded-xl border text-left transition-all flex items-center justify-between ${
                        isSelected 
                          ? 'bg-[#0A3020] border-[#10B981] shadow-md' 
                          : 'bg-[#020E08] border-emerald-900/50 hover:bg-[#072419]'
                      }`}
                    >
                      <div className="flex items-center space-x-2.5">
                        <RoleIcon className="w-4 h-4 flex-shrink-0" style={{ color: topic.roleColor }} />
                        <div>
                          <span className="text-xs font-bold text-white block truncate max-w-[190px] font-game">
                            {topic.title}
                          </span>
                          <span className="text-[10px] font-mono text-emerald-300">
                            {topic.duration} • {topic.importance}
                          </span>
                        </div>
                      </div>

                      <div className="flex items-center space-x-1.5">
                        {isMastered && (
                          <CheckCircle2 className="w-4 h-4 text-[#10B981]" />
                        )}
                        <ChevronRight className="w-3.5 h-3.5 text-slate-500" />
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* Right Column: Deep-Dive Card with Formula & Takeaway */}
              <div className="lg:col-span-7 p-4 sm:p-5 rounded-xl border border-emerald-800/50 bg-[#041C12] space-y-3.5">
                {selectedTopic && (
                  <>
                    <div className="flex justify-between items-start border-b border-emerald-800/60 pb-3">
                      <div>
                        <span className="text-[10px] font-mono font-bold uppercase text-[#FBBF24]">
                          {selectedTopic.roleName}
                        </span>
                        <h3 className="text-base sm:text-lg font-bold text-white uppercase font-game">{selectedTopic.title}</h3>
                        <p className="text-xs text-slate-300">{selectedTopic.summary}</p>
                      </div>

                      <button
                        onClick={() => handleToggleMastery(selectedTopic.id)}
                        className={`px-2.5 py-1 text-[10px] font-mono font-bold uppercase rounded-lg border transition-all flex items-center space-x-1 ${
                          masteredTopics[selectedTopic.id]
                            ? 'bg-[#10B981] text-[#02140D] border-emerald-500'
                            : 'bg-[#020B06] text-emerald-300 border-emerald-800 hover:bg-[#10B981] hover:text-[#02140D]'
                        }`}
                      >
                        <CheckCircle2 className="w-3 h-3" />
                        <span>{masteredTopics[selectedTopic.id] ? "Mastered" : "Mark Mastered"}</span>
                      </button>
                    </div>

                    {/* Formula / Rule Box */}
                    <div className="bg-[#020B06] p-3 rounded-lg border border-emerald-800/60 space-y-1">
                      <span className="text-[10px] font-mono text-[#FBBF24] font-bold block uppercase">
                        📐 Mathematical Equation / Rule
                      </span>
                      <code className="text-xs sm:text-sm font-mono font-bold text-[#10B981] block">
                        {selectedTopic.formula}
                      </code>
                    </div>

                    {/* Key Takeaway */}
                    <div className="bg-[#020E08] p-3 rounded-lg border border-emerald-900/60 space-y-1">
                      <span className="text-[10px] font-mono text-emerald-300 font-bold block uppercase">
                        💡 Key Tactical Takeaway
                      </span>
                      <p className="text-xs text-slate-300 font-medium leading-relaxed">
                        {selectedTopic.keyTakeaway}
                      </p>
                    </div>
                  </>
                )}
              </div>

            </div>
          )}

          {/* TAB 3: INTERACTIVE PRACTICE DRILLS */}
          {activeTab === 'drill' && (
            <div className="space-y-3">
              <div className="bg-[#020B06] p-3 rounded-xl border border-emerald-800/60 text-xs font-mono text-emerald-300">
                ⚡ Rapid-fire concept verification. Solve these concept checks to solidify your knowledge before re-entering the heist!
              </div>

              <div className="space-y-3">
                {plan.recommendedTopics.slice(0, 3).map((topic, tIdx) => {
                  const drill = topic.practiceDrill;
                  if (!drill) return null;
                  const currentAnswer = drillAnswers[topic.id];
                  const isSubmitted = !!drillSubmitted[topic.id];
                  const isCorrect = currentAnswer === drill.correct;

                  return (
                    <div key={topic.id} className="p-4 rounded-xl border border-emerald-800/50 bg-[#041C12] space-y-3">
                      <div className="flex justify-between items-center text-xs font-mono">
                        <span className="text-[#FBBF24] font-bold">
                          DRILL 0{tIdx + 1}: {topic.title}
                        </span>
                        <span className="text-emerald-300">{topic.roleName}</span>
                      </div>

                      <p className="text-xs sm:text-sm font-bold text-white">
                        {drill.question}
                      </p>

                      {/* Options Grid */}
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {drill.options.map((opt, optIdx) => {
                          const isSelected = currentAnswer === optIdx;
                          const isOptionCorrect = optIdx === drill.correct;

                          let btnStyle = "bg-[#020B06] text-slate-300 border-emerald-800/60 hover:bg-[#0A3020]";
                          if (isSubmitted) {
                            if (isOptionCorrect) btnStyle = "bg-[#10B981] text-[#02140D] font-bold border-emerald-600";
                            else if (isSelected && !isOptionCorrect) btnStyle = "bg-red-950 text-red-200 border-red-800";
                          } else if (isSelected) {
                            btnStyle = "bg-[#FBBF24] text-[#02140D] font-bold border-amber-500";
                          }

                          return (
                            <button
                              key={optIdx}
                              onClick={() => handleSelectDrillOption(topic.id, optIdx)}
                              disabled={isSubmitted}
                              className={`p-2.5 text-xs text-left rounded-lg border transition-all ${btnStyle}`}
                            >
                              <span className="font-mono font-bold mr-2">{String.fromCharCode(65 + optIdx)}.</span>
                              <span>{opt}</span>
                            </button>
                          );
                        })}
                      </div>

                      {/* Submit / Verification */}
                      <div className="flex justify-between items-center pt-1">
                        {isSubmitted ? (
                          <div className="flex items-center space-x-2 text-xs font-mono">
                            {isCorrect ? (
                              <span className="text-[#10B981] font-bold">✅ Correct! {drill.explanation}</span>
                            ) : (
                              <span className="text-[#FF4D6D] font-bold">❌ Incorrect. {drill.explanation}</span>
                            )}
                          </div>
                        ) : (
                          <button
                            onClick={() => handleCheckDrill(topic.id, drill.correct)}
                            disabled={currentAnswer === undefined}
                            className="bg-[#10B981] text-[#02140D] font-bold px-4 py-1.5 text-xs uppercase rounded-lg border border-emerald-600 disabled:opacity-50 hover:bg-[#34D399] font-game"
                          >
                            Verify Answer
                          </button>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

        </div>

        {/* FOOTER ACTIONS */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-3 border-t border-emerald-900/60 pt-3">
          <div className="text-xs font-mono text-emerald-300">
            <span>Status: </span>
            <span className="text-amber-300 font-bold">
              {masteredCount === plan.recommendedTopics.length ? "✨ Ready for 100% Extraction!" : "Reviewing Key Concepts"}
            </span>
          </div>

          <div className="flex items-center space-x-2.5 w-full sm:w-auto">
            <button
              onClick={onClose}
              className="flex-1 sm:flex-none bg-[#020B06] text-emerald-300 font-mono text-xs px-4 py-2 rounded-lg border border-emerald-800 hover:bg-[#072419]"
            >
              Close Roadmap
            </button>
            {onRetryWithHints && (
              <button
                onClick={onRetryWithHints}
                className="flex-1 sm:flex-none bg-[#10B981] text-[#02140D] font-bold text-xs px-4 py-2 rounded-lg hover:bg-[#34D399] uppercase flex items-center justify-center space-x-1.5 font-game shadow-md shadow-emerald-950"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Retry Mission</span>
              </button>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
