import React, { useState } from 'react';
import { 
  X, Compass, Terminal, FlaskConical, Key, Sparkles, BookOpen, 
  CheckCircle2, Clock, Award, ArrowRight, RotateCcw, ShieldAlert,
  HelpCircle, ChevronRight, Download, Share2, Lightbulb, Bookmark
} from 'lucide-react';
import { heistAudio } from './HeistAudioEngine';
import { generateRemediationPlan } from '../data/remediationData';

export default function RemediationRoadmapModal({
  isOpen,
  onClose,
  stageData,
  solvedRoles = {},
  alarmFails = 0,
  onRetryWithHints
}) {
  if (!isOpen) return null;

  const plan = generateRemediationPlan(stageData, solvedRoles, alarmFails);
  const [activeTab, setActiveTab] = useState('roadmap'); // 'roadmap', 'topics', 'drill'
  const [selectedTopicId, setSelectedTopicId] = useState(plan.recommendedTopics[0]?.id || null);
  const [masteredTopics, setMasteredTopics] = useState({});
  const [drillAnswers, setDrillAnswers] = useState({});
  const [drillSubmitted, setDrillSubmitted] = useState({});

  const roleIcons = {
    hacker: Terminal,
    engineer: Compass,
    scientist: FlaskConical,
    cryptographer: Key
  };

  const handleToggleMastery = (topicId) => {
    setMasteredTopics(prev => {
      const next = { ...prev, [topicId]: !prev[topicId] };
      heistAudio.playKeyClick();
      return next;
    });
  };

  const handleSelectDrillOption = (topicId, optIdx) => {
    if (drillSubmitted[topicId]) return;
    setDrillAnswers(prev => ({ ...prev, [topicId]: optIdx }));
    heistAudio.playKeyClick();
  };

  const handleCheckDrill = (topicId, correctIdx) => {
    setDrillSubmitted(prev => ({ ...prev, [topicId]: true }));
    const isCorrect = drillAnswers[topicId] === correctIdx;
    if (isCorrect) {
      heistAudio.playSuccessChime();
      setMasteredTopics(prev => ({ ...prev, [topicId]: true }));
    } else {
      heistAudio.playErrorTone();
    }
  };

  const handleExportRoadmap = () => {
    heistAudio.playKeyClick();
    const markdown = `# 🌲 V.A.U.L.T — Failure Remediation & Learning Roadmap
## Operation: ${plan.stageTitle}
**Estimated Study Time:** ${plan.estimatedStudyTime}
**Diagnostic Summary:** ${plan.diagnosticSummary}

### 🎯 Topics to Master:
${plan.recommendedTopics.map((t, idx) => `
#### ${idx + 1}. ${t.title} (${t.roleName})
- **Discipline:** ${t.discipline}
- **Importance:** ${t.importance} | **Duration:** ${t.duration}
- **Summary:** ${t.summary}
- **Formula / Rule:** \`${t.formula}\`
- **Key Takeaway:** ${t.keyTakeaway}
`).join('\n')}

---
*Generated by V.A.U.L.T Adaptive Heist Intelligence Engine*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `VAULT_Remediation_Roadmap_${stageData?.stageId || 'Custom'}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const selectedTopic = plan.recommendedTopics.find(t => t.id === selectedTopicId) || plan.recommendedTopics[0];
  const masteredCount = Object.values(masteredTopics).filter(Boolean).length;
  const progressPercent = Math.round((masteredCount / Math.max(1, plan.recommendedTopics.length)) * 100);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-5 bg-[#020B06]/90 backdrop-blur-xl animate-fade-in overflow-y-auto">
      <div className="forest-card max-w-5xl w-full p-5 sm:p-7 space-y-6 border-[4px] border-[#03140C] bg-[#051811] shadow-[12px_12px_0px_#020C07] max-h-[92vh] flex flex-col justify-between overflow-hidden">
        
        {/* MODAL HEADER */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 border-b-2 border-[#03140C] pb-4">
          <div className="flex items-center space-x-3">
            <div className="bg-[#FF4D6D] p-2.5 border-2 border-[#03140C] text-white shadow-[2px_2px_0px_#020C07]">
              <ShieldAlert className="w-6 h-6 animate-pulse" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <span className="bg-[#FBBF24] text-[#02140D] text-[10px] font-mono font-black px-2 py-0.5 border border-[#03140C] uppercase">
                  ADAPTIVE REMEDIATION ROADMAP
                </span>
                <span className="text-xs font-mono text-emerald-300 font-bold">
                  {plan.estimatedStudyTime} Estimated
                </span>
              </div>
              <h2 className="text-xl sm:text-2xl font-black uppercase tracking-tight text-[#F0FDF4] mt-0.5">
                Targeted Topics Learning Pathway
              </h2>
            </div>
          </div>

          <div className="flex items-center space-x-2 self-end sm:self-auto">
            <button
              onClick={handleExportRoadmap}
              className="bg-[#0A2D1F] text-emerald-200 border-2 border-[#03140C] px-3 py-1.5 text-xs font-black uppercase flex items-center space-x-1.5 hover:bg-[#10B981] hover:text-[#02140D] transition-colors shadow-[2px_2px_0px_#020C07]"
              title="Download Markdown Study Plan"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Guide</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 border-2 border-[#03140C] bg-[#020B06] text-slate-400 hover:text-white hover:bg-red-900/40"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* DIAGNOSTIC BANNER */}
        <div className="bg-[#03140C] border-2 border-emerald-900/60 p-3.5 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
          <div className="flex items-center space-x-2.5">
            <Lightbulb className="w-5 h-5 text-[#FBBF24] flex-shrink-0" />
            <p className="text-xs text-emerald-100 font-mono">
              <strong className="text-[#FBBF24]">Diagnostic Finding:</strong> {plan.diagnosticSummary}
            </p>
          </div>
          <div className="flex items-center space-x-2 text-xs font-mono text-emerald-300 bg-[#020B06] px-3 py-1 border border-emerald-800 flex-shrink-0">
            <span>Mastery: {masteredCount}/{plan.recommendedTopics.length} ({progressPercent}%)</span>
            <div className="w-16 h-2 bg-emerald-950 border border-emerald-700 overflow-hidden">
              <div className="h-full bg-[#10B981] transition-all duration-500" style={{ width: `${progressPercent}%` }} />
            </div>
          </div>
        </div>

        {/* VIEW NAVIGATION TABS */}
        <div className="flex border-b-2 border-[#03140C] bg-[#020B06] p-1 gap-1">
          {[
            { id: 'roadmap', label: '🗺️ Visual Learning Roadmap', desc: '4-Phase Mastery Path' },
            { id: 'topics', label: '📚 Recommended Topics & Formulas', desc: `${plan.recommendedTopics.length} Core Concepts` },
            { id: 'drill', label: '🧪 Interactive Practice Drills', desc: 'Mini-Knowledge Checks' }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id);
                heistAudio.playKeyClick();
              }}
              className={`flex-1 py-2 px-3 text-left transition-all border border-transparent ${
                activeTab === tab.id
                  ? 'bg-[#10B981] text-[#02140D] font-black border-[#03140C] shadow-[2px_2px_0px_#FBBF24]'
                  : 'text-emerald-300 hover:text-white hover:bg-[#071E14]'
              }`}
            >
              <span className="block text-xs sm:text-sm font-black">{tab.label}</span>
              <span className="hidden sm:block text-[10px] opacity-80 font-mono">{tab.desc}</span>
            </button>
          ))}
        </div>

        {/* MAIN BODY CONTENT AREA */}
        <div className="flex-1 overflow-y-auto pr-1 space-y-4 min-h-[340px]">
          
          {/* TAB 1: VISUAL 4-PHASE ROADMAP */}
          {activeTab === 'roadmap' && (
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                {plan.milestones.map((m, idx) => (
                  <div 
                    key={m.step}
                    className={`p-4 border-2 border-[#03140C] relative flex flex-col justify-between ${
                      idx === 0 
                        ? 'bg-[#0E3526] shadow-[3px_3px_0px_#10B981]'
                        : idx === 1
                        ? 'bg-[#072419] shadow-[3px_3px_0px_#FBBF24]'
                        : 'bg-[#03140C] opacity-90'
                    }`}
                  >
                    <div className="space-y-2">
                      <div className="flex justify-between items-center">
                        <span className="text-[10px] font-mono font-black uppercase text-[#FBBF24] bg-[#020B06] px-2 py-0.5 border border-amber-500/40">
                          PHASE 0{m.step}
                        </span>
                        {idx === 0 ? (
                          <CheckCircle2 className="w-4 h-4 text-[#10B981]" />
                        ) : (
                          <Sparkles className="w-4 h-4 text-emerald-400" />
                        )}
                      </div>
                      <h4 className="text-sm font-black uppercase text-[#F0FDF4]">{m.title}</h4>
                      <p className="text-[11px] text-emerald-200 leading-relaxed font-medium">{m.desc}</p>
                    </div>

                    <button
                      onClick={() => {
                        if (idx === 1) setActiveTab('topics');
                        if (idx === 2) setActiveTab('drill');
                        if (idx === 3 && onRetryWithHints) onRetryWithHints();
                        heistAudio.playKeyClick();
                      }}
                      className="mt-4 w-full bg-[#020B06] text-emerald-300 font-mono text-[10px] font-bold py-1.5 border border-emerald-700 hover:bg-[#10B981] hover:text-[#02140D] transition-colors uppercase"
                    >
                      {idx === 0 ? "Diagnosed" : idx === 1 ? "Explore Topics →" : idx === 2 ? "Take Drills →" : "Launch Retry →"}
                    </button>
                  </div>
                ))}
              </div>

              {/* Roles Breakdown Grid */}
              <div className="bg-[#03140C] p-4 border-2 border-emerald-900/60 space-y-3">
                <div className="flex justify-between items-center">
                  <h3 className="text-xs font-mono font-black uppercase text-emerald-300">
                    Targeted Discipline Focus for This Operation
                  </h3>
                  <span className="text-[10px] font-mono text-emerald-400">
                    {plan.focusRoles.length} Active STEM Sectors
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {plan.focusRoles.map(roleKey => {
                    const guide = plan.recommendedTopics.find(t => t.roleKey === roleKey);
                    const RoleIcon = roleIcons[roleKey] || Terminal;
                    const isFailed = plan.failedRoles.includes(roleKey);

                    return (
                      <div 
                        key={roleKey}
                        className={`p-3 border-2 border-[#03140C] flex items-center justify-between ${
                          isFailed ? 'bg-[#1C0D12] border-red-900/80' : 'bg-[#072419]'
                        }`}
                      >
                        <div className="flex items-center space-x-3">
                          <div className="p-2 border border-[#03140C] bg-[#020B06]" style={{ color: guide?.roleColor || '#10B981' }}>
                            <RoleIcon className="w-5 h-5" />
                          </div>
                          <div>
                            <span className="text-xs font-black uppercase text-[#F0FDF4] block">
                              {guide?.roleName || roleKey}
                            </span>
                            <span className="text-[10px] font-mono text-emerald-300">
                              {guide?.discipline}
                            </span>
                          </div>
                        </div>

                        <span className={`text-[10px] font-mono font-black px-2 py-0.5 uppercase ${
                          isFailed ? 'bg-red-900 text-white' : 'bg-emerald-900 text-emerald-200'
                        }`}>
                          {isFailed ? '⚠️ Unsolved Chamber' : '✅ Cleared Gate'}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: RECOMMENDED TOPICS & FORMULAS */}
          {activeTab === 'topics' && (
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
              
              {/* Left Column: Topic List Selector */}
              <div className="lg:col-span-5 space-y-2 max-h-[320px] overflow-y-auto pr-1">
                {plan.recommendedTopics.map((topic) => {
                  const isSelected = selectedTopic?.id === topic.id;
                  const isMastered = !!masteredTopics[topic.id];
                  const RoleIcon = roleIcons[topic.roleKey] || Terminal;

                  return (
                    <button
                      key={topic.id}
                      onClick={() => {
                        setSelectedTopicId(topic.id);
                        heistAudio.playKeyClick();
                      }}
                      className={`w-full p-3 border-2 border-[#03140C] text-left transition-all flex items-center justify-between ${
                        isSelected 
                          ? 'bg-[#0A3020] border-[#10B981] shadow-[2px_2px_0px_#FBBF24]' 
                          : 'bg-[#03140C] hover:bg-[#072419]'
                      }`}
                    >
                      <div className="flex items-center space-x-2.5">
                        <RoleIcon className="w-4 h-4 flex-shrink-0" style={{ color: topic.roleColor }} />
                        <div>
                          <span className="text-xs font-bold text-[#F0FDF4] block truncate max-w-[200px]">
                            {topic.title}
                          </span>
                          <span className="text-[10px] font-mono text-emerald-300">
                            {topic.duration} • {topic.importance}
                          </span>
                        </div>
                      </div>

                      <div className="flex items-center space-x-1.5">
                        {isMastered && (
                          <CheckCircle2 className="w-4 h-4 text-[#10B981]" />
                        )}
                        <ChevronRight className="w-3.5 h-3.5 text-slate-500" />
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* Right Column: Deep-Dive Card with Formula & Takeaway */}
              <div className="lg:col-span-7 forest-glass p-4 sm:p-5 border-2 border-[#03140C] bg-[#072419] space-y-4">
                {selectedTopic && (
                  <>
                    <div className="flex justify-between items-start border-b border-emerald-800/60 pb-3">
                      <div>
                        <span className="text-[10px] font-mono font-black uppercase text-[#FBBF24]">
                          {selectedTopic.roleName}
                        </span>
                        <h3 className="text-lg font-black text-[#F0FDF4] uppercase">{selectedTopic.title}</h3>
                        <p className="text-xs text-emerald-200">{selectedTopic.summary}</p>
                      </div>

                      <button
                        onClick={() => handleToggleMastery(selectedTopic.id)}
                        className={`px-2.5 py-1 text-[10px] font-mono font-bold uppercase border border-[#03140C] transition-all flex items-center space-x-1 ${
                          masteredTopics[selectedTopic.id]
                            ? 'bg-[#10B981] text-[#02140D]'
                            : 'bg-[#020B06] text-emerald-300 hover:bg-[#10B981] hover:text-[#02140D]'
                        }`}
                      >
                        <CheckCircle2 className="w-3 h-3" />
                        <span>{masteredTopics[selectedTopic.id] ? "Mastered" : "Mark Mastered"}</span>
                      </button>
                    </div>

                    {/* Formula / Rule Box */}
                    <div className="bg-[#020B06] p-3 border border-emerald-700/60 space-y-1">
                      <span className="text-[10px] font-mono text-[#FBBF24] font-bold block uppercase">
                        📐 Core Mathematical Equation / Syntax Rule
                      </span>
                      <code className="text-xs sm:text-sm font-mono font-black text-[#10B981] block">
                        {selectedTopic.formula}
                      </code>
                    </div>

                    {/* Key Takeaway */}
                    <div className="bg-[#03140C] p-3 border border-emerald-900 space-y-1">
                      <span className="text-[10px] font-mono text-emerald-300 font-bold block uppercase">
                        💡 Key Tactical Takeaway
                      </span>
                      <p className="text-xs text-emerald-100 font-medium leading-relaxed">
                        {selectedTopic.keyTakeaway}
                      </p>
                    </div>

                    {/* External Learning Resources */}
                    {selectedTopic.resources && (
                      <div className="space-y-1 pt-1">
                        <span className="text-[10px] font-mono text-emerald-400 font-bold block uppercase">
                          🔗 Curated Learning References
                        </span>
                        <div className="flex flex-wrap gap-2">
                          {selectedTopic.resources.map((res, rIdx) => (
                            <span key={rIdx} className="text-[10px] font-mono bg-[#020B06] text-emerald-300 px-2 py-0.5 border border-emerald-800">
                              📖 {res}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </>
                )}
              </div>

            </div>
          )}

          {/* TAB 3: INTERACTIVE PRACTICE DRILLS */}
          {activeTab === 'drill' && (
            <div className="space-y-4">
              <div className="bg-[#020B06] p-3 border border-emerald-800 text-xs font-mono text-emerald-300">
                ⚡ Rapid-fire concept verification. Solve these concept checks to solidify your knowledge before re-entering the heist!
              </div>

              <div className="space-y-4">
                {plan.recommendedTopics.slice(0, 3).map((topic, tIdx) => {
                  const drill = topic.practiceDrill;
                  if (!drill) return null;
                  const currentAnswer = drillAnswers[topic.id];
                  const isSubmitted = !!drillSubmitted[topic.id];
                  const isCorrect = currentAnswer === drill.correct;

                  return (
                    <div key={topic.id} className="forest-glass p-4 border-2 border-[#03140C] bg-[#072419] space-y-3">
                      <div className="flex justify-between items-center text-xs font-mono">
                        <span className="text-[#FBBF24] font-bold">
                          DRILL 0{tIdx + 1}: {topic.title}
                        </span>
                        <span className="text-emerald-300">{topic.roleName}</span>
                      </div>

                      <p className="text-xs sm:text-sm font-bold text-[#F0FDF4]">
                        {drill.question}
                      </p>

                      {/* Options Grid */}
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {drill.options.map((opt, optIdx) => {
                          const isSelected = currentAnswer === optIdx;
                          const isOptionCorrect = optIdx === drill.correct;

                          let btnStyle = "bg-[#020B06] text-emerald-200 border-emerald-800/80 hover:bg-[#0A3020]";
                          if (isSubmitted) {
                            if (isOptionCorrect) btnStyle = "bg-[#10B981] text-[#02140D] font-black border-[#03140C]";
                            else if (isSelected && !isOptionCorrect) btnStyle = "bg-red-900 text-white border-red-700";
                          } else if (isSelected) {
                            btnStyle = "bg-[#FBBF24] text-[#02140D] font-black border-[#03140C]";
                          }

                          return (
                            <button
                              key={optIdx}
                              onClick={() => handleSelectDrillOption(topic.id, optIdx)}
                              disabled={isSubmitted}
                              className={`p-2.5 text-xs text-left border transition-all ${btnStyle}`}
                            >
                              <span className="font-mono font-bold mr-2">{String.fromCharCode(65 + optIdx)}.</span>
                              <span>{opt}</span>
                            </button>
                          );
                        })}
                      </div>

                      {/* Submit / Verification */}
                      <div className="flex justify-between items-center pt-2">
                        {isSubmitted ? (
                          <div className="flex items-center space-x-2 text-xs font-mono">
                            {isCorrect ? (
                              <span className="text-[#10B981] font-black">✅ Correct! {drill.explanation}</span>
                            ) : (
                              <span className="text-[#FF4D6D] font-black">❌ Incorrect. {drill.explanation}</span>
                            )}
                          </div>
                        ) : (
                          <button
                            onClick={() => handleCheckDrill(topic.id, drill.correct)}
                            disabled={currentAnswer === undefined}
                            className="bg-[#10B981] text-[#02140D] font-black px-4 py-1.5 text-xs uppercase border border-[#03140C] disabled:opacity-50 hover:bg-[#34D399]"
                          >
                            Verify Answer
                          </button>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

        </div>

        {/* FOOTER ACTIONS */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-3 border-t-2 border-[#03140C] pt-4">
          <div className="text-xs font-mono text-emerald-300">
            <span>Status: </span>
            <span className="text-[#FBBF24] font-bold">
              {masteredCount === plan.recommendedTopics.length ? "✨ Ready for 100% Vault Extraction!" : "Reviewing Key STEM Concepts"}
            </span>
          </div>

          <div className="flex items-center space-x-3 w-full sm:w-auto">
            <button
              onClick={onClose}
              className="flex-1 sm:flex-none bg-[#020B06] text-emerald-300 font-mono text-xs px-4 py-2.5 border-2 border-[#03140C] hover:bg-[#072419]"
            >
              Close Roadmap
            </button>
            {onRetryWithHints && (
              <button
                onClick={onRetryWithHints}
                className="flex-1 sm:flex-none bg-[#10B981] text-[#02140D] font-black text-xs px-5 py-2.5 border-[3px] border-[#03140C] shadow-[3px_3px_0px_#020C07] hover:bg-[#34D399] active:translate-x-0.5 uppercase flex items-center justify-center space-x-1.5"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Retry Mission With Hints</span>
              </button>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
